### ISSUE TITLE
fatal error No such file or directory. C++ header files cannot be found.

### ISSUE THREAD

**Issue by canberkgurel** [luxonis/depthai-ros-examples#10]
I'm having the `No such file or directory` error when I try to build my catkin_ws. C++ header files cannot be found.

`Errors     << depthai_examples:make /home/ubuntu/catkin_ws/logs/depthai_examples/build.make.002.log
/home/ubuntu/catkin_ws/src/depthai-ros-examples/depthai_examples/lib/rgb_pipeline.cpp:1:10: fatal error: depthai_examples/rgb_pipeline.hpp: No such file or directory
 #include <depthai_examples/rgb_pipeline.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/depthai_examples.dir/lib/rgb_pipeline.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/ubuntu/catkin_ws/src/depthai-ros-examples/depthai_examples/lib/rgb_stereo_pipeline.cpp:1:10: fatal error: depthai_examples/rgb_stereo_pipeline.hpp: No such file or directory
 #include <depthai_examples/rgb_stereo_pipeline.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/ubuntu/catkin_ws/src/depthai-ros-examples/depthai_examples/lib/stereo_from_host.cpp:1:10: fatal error: depthai_examples/stereo_from_host.hpp: No such file or directory
 #include <depthai_examples/stereo_from_host.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/depthai_examples.dir/lib/rgb_stereo_pipeline.cpp.o] Error 1
make[2]: *** [CMakeFiles/depthai_examples.dir/lib/stereo_from_host.cpp.o] Error 1
make[1]: *** [CMakeFiles/depthai_examples.dir/all] Error 2
make: *** [all] Error 2
`

I tried sourcing ` /opt/ros/melodic/setup.bash` but that didn't solve it.

**Comment by saching13** [comment]
Hey Canberk,
    I spun a new Ubuntu 18.04 docker and tried the complete steps, but I was not able to reach this error. 
Can you try deleting the `devel` and `build` followed by updating the repository and giving it a shot again. 
if it doesn't work can you provide the steps you carried out and on which system so that I can recreate this.

**Comment by canberkgurel** [comment]
@saching13 Let's compare notes, what steps have you taken?

**Comment by saching13** [comment]
I spun up `ros-base` melodic docker and just followed all the steps [here](https://github.com/luxonis/depthai-ros) without a single modification.

**Comment by canberkgurel** [comment]
@saching13 This is what I'm seeing:

```
~/catkin_ws$ wget https://raw.githubusercontent.com/luxonis/depthai-ros/noetic-devel/underlay.repos
--2021-08-25 17:14:25--  https://raw.githubusercontent.com/luxonis/depthai-ros/noetic-devel/underlay.repos
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 261 [text/plain]
Saving to: ‘underlay.repos’

underlay.repos      100%[===================>]     261  --.-KB/s    in 0s      

2021-08-25 17:14:25 (1.48 MB/s) - ‘underlay.repos’ saved [261/261]
```

```
~/catkin_ws$ vcs import src < underlay.repos
..
=== src/luxonis/depthai-ros (git) ===
Cloning into '.'...
=== src/luxonis/depthai-ros-examples (git) ===
Cloning into '.'...
```

```
~/catkin_ws$ rosdep install --from-paths src --ignore-src -r -y
#All required rosdeps installed successfully
~/catkin_ws$ source /opt/ros/melodic/setup.bash
~/catkin_ws$ catkin build
-----------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/melodic
Workspace:                   /home/ubuntu/catkin_ws
-----------------------------------------------------------
Build Space:        [exists] /home/ubuntu/catkin_ws/build
Devel Space:        [exists] /home/ubuntu/catkin_ws/devel
Install Space:      [unused] /home/ubuntu/catkin_ws/install
Log Space:          [exists] /home/ubuntu/catkin_ws/logs
Source Space:       [exists] /home/ubuntu/catkin_ws/src
DESTDIR:            [unused] None
-----------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-----------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-----------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-----------------------------------------------------------
Workspace configuration appears valid.
-----------------------------------------------------------
[build] Found '9' packages in 0.0 seconds.                                                     
[build] Updating package table.                                                                
Starting  >>> depthai_ros_msgs                                                                 
Starting  >>> mavlink                                                                          
Starting  >>> mavros_msgs                                                                      
_______________________________________________________________________________________________
Errors     << depthai_ros_msgs:check /home/ubuntu/catkin_ws/logs/depthai_ros_msgs/build.check.002.log
CMake Error: The source directory "/home/ubuntu/catkin_ws/src/depthai-ros/depthai_ros_msgs" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** [cmake_check_build_system] Error 1
cd /home/ubuntu/catkin_ws/build/depthai_ros_msgs; catkin build --get-env depthai_ros_msgs | catkin env -si  /usr/bin/make cmake_check_build_system; cd -
...............................................................................................
Failed     << depthai_ros_msgs:check          [ Exited with code 2 ]                           
Failed    <<< depthai_ros_msgs                [ 0.7 seconds ]                                  
Abandoned <<< depthai_bridge                  [ Unrelated job failed ]                         
Abandoned <<< depthai_examples                [ Unrelated job failed ]                         
Abandoned <<< libmavconn                      [ Unrelated job failed ]                         
Abandoned <<< mavros                          [ Unrelated job failed ]                         
Abandoned <<< mavros_extras                   [ Unrelated job failed ]                         
Abandoned <<< test_mavros                     [ Unrelated job failed ]                         
Finished  <<< mavlink                         [ 6.7 seconds ]                                  
Finished  <<< mavros_msgs                     [ 11.9 seconds ]                                 
[build] Summary: 2 of 9 packages succeeded.                                                    
[build]   Ignored:   None.                                                                     
[build]   Warnings:  None.                                                                     
[build]   Abandoned: 6 packages were abandoned.                                                
[build]   Failed:    1 packages failed.                                                        
[build] Runtime: 12.7 seconds total. 
```

**Comment by canberkgurel** [comment]
I'll run catkin clean and catkin build one more time. Because the error is different now.

**Comment by saching13** [comment]
I see the diff in execution steps too.
any specific reason you prefer `catkin build` over `catkin_make` or `catkin_make_isolated`? 
I haven't tested with `catkin build`. I can take a look at how the build changes that it is affecting.

**Comment by canberkgurel** [comment]
@saching13 The main reason is that the other packages in my workspace are designed to be built with catkin build. I'm currently building the workspace, it's going fine so far. It usually takes about 15-17 minutes to build everything.

**Comment by saching13** [comment]
Thanks for the details. I will modify the packages to support `catkin build` too. 
I am not sure why it is taking 15 min though. Mine happens less than 5 min. Can you share the system specs so that I can try and recreate it ?

**Comment by canberkgurel** [comment]
@saching13 It takes a very long time because of the other packages other than the depthai packages. no need to worry about it. The build process is completed with success. I'll go ahead an close the issue. Thanks for assistance!
