### ISSUE TITLE
Noisy Pointcloud after launching the stereo_node.launch

### ISSUE THREAD

**Issue by hardesh-peppermint** [luxonis/depthai-ros-examples#13]
Hi,

I just got a new OAK D 2 days ago. I've been tinkering with the camera. I noticed that the camera's giving very noisy pointcloud. I could find a solution online. I've uploaded a [bag file](https://drive.google.com/drive/folders/1eBkMXG3zH-D0YMHjwWTZ89fTIv0ybdNo?usp=sharing) in case you want to take a look at the pointcloud and the images. 

Kindly look into this. 

Thanks,
Harshal

**Comment by hardesh-peppermint** [comment]
Hi,

Joined the discord channel after posting this issue. I'll be trying out the lastest commit on depthai-core. Will let you know if the performance improves.

**Comment by saching13** [comment]
Is this ROS1 or ROS2 ?.

**Comment by hardesh-peppermint** [comment]
I'm using ROS1. 

Performance improved significantly after installing the latest version of depthai-core. There's still some noise, but I think that can be removed by filtering.

**Comment by saching13** [comment]
Some noise is still there since it is raw depth. We are working on some post processing which will be included in upcoming releases

**Comment by hardesh-peppermint** [comment]
Thanks for letting me know. Looking forward towards newer releases 😄 

We can close this issue if you want.

**Comment by saching13** [comment]
Thank you.
