### ISSUE TITLE
Galactic support

### ISSUE THREAD

**Issue by k-gupta** [luxonis/depthai-ros-examples#14]
Hello, 

We want to use these ROS packages but we noticed that there is no Galactic one. Is there a roadmap to add this support? 

Thanks!

**Comment by saching13** [comment]
you can use [this](https://github.com/luxonis/depthai-ros-examples/tree/noetic-foxy-integrate-wip) with galactic branch of [depthai-ros](https://github.com/luxonis/depthai-ros/tree/galactic-devel) But since the examples is WIP launch files are not available. I should have them by next week.

**Comment by saching13** [comment]
Galactic is supported on main for some time now.
Closing this issue.
