### ISSUE TITLE
/depthai-ros-examples/depthai_examples/ros1_src/stereo_nodelet.cpp bug!

### ISSUE THREAD

**Issue by tosa-no-onchan** [luxonis/depthai-ros-examples#22]
Hi!
Would you update some code?

/depthai-ros-examples/depthai_examples/ros1_src/stereo_nodelet.cpp
...
line 148
    std::tuple<dai::Pipeline, int, int> createPipeline(bool withDepth, bool lrcheck, bool extended, bool subpixel, int confidence, int LRchecktresh, std::string resolution){
        dai::Pipeline pipeline;
        ...
        // MonoCamera
        //monoLeft->setResolution(dai::MonoCameraProperties::SensorResolution::THE_720_P);
        monoLeft->setResolution(monoResolution);    // here
        monoLeft->setBoardSocket(dai::CameraBoardSocket::LEFT);
        //monoRight->setResolution(dai::MonoCameraProperties::SensorResolution::THE_720_P);
        monoRight->setResolution(monoResolution);   //  here
        monoRight->setBoardSocket(dai::CameraBoardSocket::RIGHT);
        ...

**Comment by saching13** [comment]
Sorry for the issue.
cc: @daxoft

**Comment by saching13** [comment]
Fixed it.

**Comment by tosa-no-onchan** [comment]
Thank you for your early response,seaching13.
It worked!

I am testing with OAK-D-Lite.
On PC Ubuntu Mate 18.04 and ROS melodic.
