### ISSUE TITLE
Publisher with blocking dataqueue

### ISSUE THREAD

**Issue by psFournier** [luxonis/depthai-ros-examples#33]
Hello,
The mobilenet_publisher.cpp example says that the addPublisherCallback call "works only when the dataqueue is non-blocking". I have checked the source code for the BridgePublisher, but my C++ is rusty so I failed to get where this limitation comes from.
Let's say I need to work with blocking dataqueues (matching passthrough frames and their original frames), could you elaborate on what would be the issue ?
Thanks you in advance !

**Comment by saching13** [comment]
The limitation is coming from `depthai-core` library where the queue acts differently when it is blocked and Callback methods doesn't work at that time.
