### ISSUE TITLE
Weird disparity values being published in stereo_node

### ISSUE THREAD

**Issue by psFournier** [luxonis/depthai-ros-examples#36]
Hello,
I am trying to retrieve a disparity image from the stereo_node publisher with mode != depth, and the values observed, be it from a subscriber to .../stereo/disparity or with a rostopic echo .../stereo/disparity, seem off: 
most are 0 with some integer values scattered everywhere. I checked that the disparity image obtained directly from the device with a getFrame call does not produce these values but "proper values" ranging between 1 and 255.

Also, I noticed with rostopic echo that the delta_d attribute of the published DisparityImage is 0.0, whereas the source code for the DisparityConverter seems to produce values that are either 1 or 1/32.

Could these two observations be related ?
Thanks in advance

**Comment by saching13** [comment]
Sorry for the issue. We are looking into it.

**Comment by daxoft** [comment]
Hi, can you try to turn subpixel off? As for the delta error, it was a cast bug, it will be merge into main soon, if you need it fixed now you can try this branch for the depthai-ros repo: https://github.com/luxonis/depthai-ros/tree/daxoft/fix_disparity

**Comment by saching13** [comment]
@psFournier  Can you check this viewer to verify ? the image looks good to me, 
` rosrun image_view disparity_view image:=/stereo_publisher/stereo/disparity`

**Comment by saching13** [comment]
![image](https://user-images.githubusercontent.com/43363595/163442510-4888b359-866c-4add-bc1b-c4693bc4fe5e.png)

**Comment by FPSychotic** [comment]
Same me I think, but I didn't make test. Just black disparity with
normalised ticked or not. ROS2 warp branch

**Comment by psFournier** [comment]
Hello,
Thank you for the quick replies !

Things I checked : 
- `stereo_node.launch mode:=disp`, with or without subpixel : `rosrun image_view disparity_view image:=/stereo_publisher/stereo/disparity` produces the image above as expected, but `rostopic echo -n1 /stereo_publisher/stereo/disparity` produces values for disparity that seem weird to me (allmost all 0 and some integer values). Perhaps it's just a side effect of how echo reads the data, so that may not be a problem.
- subpixel=true produces a delta_d attribute value 0.0, subpixel=false produces a delta_d attribute value of 1. I will check if the branch devel with the fix for the cast solves the case with subpixel=true.

The issue I wanted to point out comes when I try to subscribe to /depthai_publisher/stereo/disparity and store the disparity for further processing.
```
disp_callback(disp_msg):
        img_msg = disp_msg.image
        disp = cv_bridge.imgmsg_to_cv2(img_msg)
```
followed by `cv2.imshow("disp", disp)` produces a black image.

 I went to the source code of imgmsg_to_cv2 and the black output is caused by lines 177-178:
`
if img_msg.is_bigendian == (sys.byteorder == 'little'):
            im = im.byteswap().newbyteorder()
`
When replacing imgmsg_to_cv2 with its source code (for the case n_channels=1) and without these lines, the output looks better: 
![image](https://user-images.githubusercontent.com/9402290/163998457-0a470535-89d3-42d0-9019-46c963668917.png)

For all that,  even in this case where imshow seems to work, if I check np.min(disp) and np.max(disp), the outputs are something like 0 and 8e-41, which don't look like proper disparity values...

Do you have any of what's happenning there ? Thanks in advance !

**Comment by psFournier** [comment]
A minimal working example to reproduce the image above with 0.0 and 8.0e-41 as min and max disp values : 
```
from stereo_msgs.msg import DisparityImage
from cv_bridge import CvBridge
import cv2
import sys
import numpy as np
import rospy


class Disp:

    def __init__(self):
        self.br = CvBridge()
        self.disp = None
        rospy.Subscriber('/depthai_publisher/stereo/disparity', DisparityImage, self.callback)

    def callback(self, data):
        img_msg = data.image
        try:
            dtype, n_channels = self.br.encoding_to_dtype_with_channels(img_msg.encoding)
            dtype = np.dtype(dtype)
            dtype = dtype.newbyteorder('>' if img_msg.is_bigendian else '<')
            self.disp = np.ndarray(shape=(img_msg.height, img_msg.width), 
                                   dtype=dtype, buffer=img_msg.data)
        except CvBridgeError as e:
            print(e)
        print(np.min(self.disp), np.max(self.disp))
        cv2.imshow("disp", self.disp)
        cv2.waitKey(1)

def main():
    rospy.init_node('node', anonymous=True)
    disp = Disp()
    rospy.spin()
    cv2.destroyAllWindows()

if __name__ == '__main__':
    main()  
```

**Comment by danilo-pejovic** [comment]
Hey, sorry for random ping year later. We are repurposing this repo for non-critical ROS examples we develop over time. If this issue is still relevant let me know and we can move this discussion to depthai-ros.
