### ISSUE TITLE
OAK-D Pro W Dev  ROS and ROS2 support add basic options equally to every example

### ISSUE THREAD

**Issue by FPSychotic** [luxonis/depthai-ros-examples#37]
Please give support to OAK-D Pro W Dev  in all 
ROS/ROS2 examples .
I received the camera 3 weeks ago but I only was able so stream the stereo topics without depth (no depth data but published).

Another different problem is different examples have different options, even the basic ones that should be common in all of them as resolution, rectification, etc.

I can see the camera advertised in "ROS" discurse while it cannot be considered supported IMHO.

Any timeline to add it?

**Comment by saching13** [comment]
Hello,
Use the branch in the PR to install the depthai-core. That will fix the depth problem considering your device is calibrated. No update req for depthai-ros

https://github.com/luxonis/depthai-core/pull/437

**Comment by FPSychotic** [comment]
That is the PR I have installed. It only give me 2 stereo streams and the depth is published, but very weird. Maybe is just bad visualization in rviz but anyways It don't allow me use stereo_inertial or anything with rgb camera as rgb stereo example. I need the IMU and rgb and that is not working.
For other side If I connect OAK-D  instead the Pro W to have color, it makes artifacts due to a bug in the opencv mesh function. 
Is what resulted from  the Discord but nothing changed it looks.
No sure if luxonis can reproduce the error, what is a bug and what is job that needs be done by luxonis, but right now in my case, with the things advised in Discord, from I got the camera three weeks ago, ROS is not working, and now OAK-D is bugged too

**Comment by FPSychotic** [comment]
https://youtu.be/3ci0qoSXKbc
This is the problem I get with OAK-D and that branch. In Pro-W I think worked better, but blurred corners

**Comment by saching13** [comment]
Ah ok. Sorry. looks like I missed the conv on discord. Let me test it and get back. 

In the meantime can you check if you see the same artifacts on [this](https://github.com/luxonis/depthai-python/blob/main/examples/StereoDepth/stereo_depth_video.py) python example in main  with `-lm` argument ?

**Comment by FPSychotic** [comment]
I tested both cameras with -lm and without it. 
-PRO W Dev , With -lm gets depth in a reasonable pattern, in ROS2 doesn't , depth has a lot less noise than without -lm, , better framerate as without -lm gets laggy. corners still blurred in both.
![lm depth](https://user-images.githubusercontent.com/36112212/163729843-f606bb24-60eb-4253-8fac-5bd334a5a0ef.png)
![lm ir](https://user-images.githubusercontent.com/36112212/163729844-a76729c3-cbb9-4858-91f8-d436df397a8d.png)
![no lm depth](https://user-images.githubusercontent.com/36112212/163729846-d6385c6a-f118-4e13-a87d-cc3e8f454c53.png)
![no lm ir](https://user-images.githubusercontent.com/36112212/163729847-4cbe0df6-0c4f-4604-a7be-eecc16aba494.png)


-OAK-D, now the artefacts are not, no even the misalignment one I showed in discord, but in the depth, I can see clearly that both errors, misalignment and distortions, just like the depth is made from the bugged ones, no the ones that appears now. 
That is very weird, is like depth is not from the displayed images, no idea.

**Comment by saching13** [comment]
![image](https://user-images.githubusercontent.com/43363595/163883450-61c84833-cb21-420b-ae65-83eb9b9bf8c0.png)

![image](https://user-images.githubusercontent.com/43363595/163885368-1a7df5ee-acc3-4385-903a-7a61426a85be.png)

This is my OAK-D-W. and it is using the `warp_mesh_on_device`. I don't see any issues with using it on this branch with depthai-ros

On the artifacts in OAK-D. it is coming from OpenCV calibration. I'm looking into it.

**Comment by FPSychotic** [comment]
I'm in ROS2 is that ROS2?. Is it inertial-stereo example? , Are working the rgb examples?.
I will need it for ROS1 too.

**Comment by saching13** [comment]
> I'm in ROS2 is that ROS2?.

Yes it is ros2. 

> Is it inertial-stereo example? 

First image is not. Second image is. 

>  Are working the rgb examples?.

What is this ? We don't have rectification added for RGB. we will have to add in the FW or add an ImageManip node to do that.

**Comment by saching13** [comment]
Everything that works on ROS2 will work on ROS1.

**Comment by FPSychotic** [comment]
So rgb exmples not working?

For what add something that leave a sensor off of game?

Could be that any panameter in my inertial stereo example is calling a RGB function and because that stereo inertial crash?

If not, Im afraid that I received another camera without calibration

**Comment by saching13** [comment]
All dev versions of devices are not factory calibrated. 

> So rgb exmples not working?

I'm not understanding what you mean. Can you share which RGB example is not working so that I can check ?

> Could be that any panameter in my inertial stereo example is calling a RGB function and because that stereo inertial crash?

Stil not clear. Please share the command used. And the error.

**Comment by FPSychotic** [comment]
"What is this ? We don't have rectification added for RGB. we will have to add in the FW or add an ImageManip node to do that."

Any rgb/spatial example that use rgb camera.
Before change to mesh system, was rectified the RGB in camera or in host? How could be  colororized the pointclouds then?

**Comment by FPSychotic** [comment]
![Uploading 20220409_182637-1.jpg…]()

**Comment by FPSychotic** [comment]
Alex and Nejc said it is calibrated .
Alex said something should be added in ROS.
Szhabi said something is bugged and something need be added to ROS.
You said something should be added in ROS 3 weeks ago.
I cannot paste, remember or test all the done in 60msg in discord.
To avoid any confusion,If everything works in your case, examples of yolo, rgb stereo, inertial stereo and stereo, can you tell me , what branch of DepthAI core, and What branch of ROS2 and ROS1 do I need to use with OAK-D-PRO W dev to install them again?

**Comment by FPSychotic** [comment]
> I'm not understanding what you mean. Can you share which RGB example is not working so that I can check ?

If I run stereo_inertial_node 
`igcs@igcs:~$ ros2 launch depthai_examples stereo_inertial_node.launch.py
[INFO] [launch]: All log files can be found below /home/igcs/.ros/log/2022-04-19-07-55-42-890342-igcs-4655
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [stereo_inertial_node-1]: process started with pid [4670]
[INFO] [robot_state_publisher-2]: process started with pid [4672]
[INFO] [component_container-3]: process started with pid [4674]
[INFO] [component_container-4]: process started with pid [4676]
[INFO] [rviz2-5]: process started with pid [4678]
[robot_state_publisher-2] Parsing robot urdf xml string.
[robot_state_publisher-2] Link oak-d_frame had 5 children
[robot_state_publisher-2] Link oak_imu_frame had 0 children
[robot_state_publisher-2] Link oak_left_camera_frame had 1 children
[robot_state_publisher-2] Link oak_left_camera_optical_frame had 0 children
[robot_state_publisher-2] Link oak_model_origin had 0 children
[robot_state_publisher-2] Link oak_rgb_camera_frame had 1 children
[robot_state_publisher-2] Link oak_rgb_camera_optical_frame had 0 children
[robot_state_publisher-2] Link oak_right_camera_frame had 1 children
[robot_state_publisher-2] Link oak_right_camera_optical_frame had 0 children
[robot_state_publisher-2] [INFO] [1650351343.116838981] [oak_state_publisher]: got segment oak-d-base-frame
[robot_state_publisher-2] [INFO] [1650351343.116903378] [oak_state_publisher]: got segment oak-d_frame
[robot_state_publisher-2] [INFO] [1650351343.116913994] [oak_state_publisher]: got segment oak_imu_frame
[robot_state_publisher-2] [INFO] [1650351343.116923843] [oak_state_publisher]: got segment oak_left_camera_frame
[robot_state_publisher-2] [INFO] [1650351343.116934389] [oak_state_publisher]: got segment oak_left_camera_optical_frame
[robot_state_publisher-2] [INFO] [1650351343.116944028] [oak_state_publisher]: got segment oak_model_origin
[robot_state_publisher-2] [INFO] [1650351343.116953457] [oak_state_publisher]: got segment oak_rgb_camera_frame
[robot_state_publisher-2] [INFO] [1650351343.116963445] [oak_state_publisher]: got segment oak_rgb_camera_optical_frame
[robot_state_publisher-2] [INFO] [1650351343.116974062] [oak_state_publisher]: got segment oak_right_camera_frame
[robot_state_publisher-2] [INFO] [1650351343.116984049] [oak_state_publisher]: got segment oak_right_camera_optical_frame
[component_container-3] [INFO] [1650351343.339841596] [container]: Load Library: /opt/ros/foxy/lib/libdepth_image_proc.so
[component_container-4] [INFO] [1650351343.341705210] [container2]: Load Library: /opt/ros/foxy/lib/libdepth_image_proc.so
[component_container-3] [INFO] [1650351343.361529355] [container]: Found class: rclcpp_components::NodeFactoryTemplate<depth_image_proc::ConvertMetricNode>
[component_container-3] [INFO] [1650351343.362063044] [container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<depth_image_proc::ConvertMetricNode>
[component_container-4] [INFO] [1650351343.362286619] [container2]: Found class: rclcpp_components::NodeFactoryTemplate<depth_image_proc::ConvertMetricNode>
[component_container-4] [INFO] [1650351343.362318748] [container2]: Found class: rclcpp_components::NodeFactoryTemplate<depth_image_proc::CropForemostNode>
[component_container-4] [INFO] [1650351343.362331180] [container2]: Found class: rclcpp_components::NodeFactoryTemplate<depth_image_proc::DisparityNode>
[component_container-4] [INFO] [1650351343.362342635] [container2]: Found class: rclcpp_components::NodeFactoryTemplate<depth_image_proc::PointCloudXyzNode>
[component_container-4] [INFO] [1650351343.362353042] [container2]: Found class: rclcpp_components::NodeFactoryTemplate<depth_image_proc::PointCloudXyzRadialNode>
[component_container-4] [INFO] [1650351343.362365055] [container2]: Found class: rclcpp_components::NodeFactoryTemplate<depth_image_proc::PointCloudXyziNode>
[component_container-4] [INFO] [1650351343.362376440] [container2]: Instantiate class: rclcpp_components::NodeFactoryTemplate<depth_image_proc::PointCloudXyziNode>
[component_container-3] /opt/ros/foxy/lib/rclcpp_components/component_container: symbol lookup error: /opt/ros/foxy/lib/libdepth_image_proc.so: undefined symbol: _ZN15image_transport19create_subscriptionEPN6rclcpp4NodeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt8functionIFvRKSt10shared_ptrIKN11sensor_msgs3msg6Image_ISaIvEEEEEESA_17rmw_qos_profile_t
[component_container-4] /opt/ros/foxy/lib/rclcpp_components/component_container: symbol lookup error: /opt/ros/foxy/lib/libdepth_image_proc.so: undefined symbol: _ZN15image_transport19create_subscriptionEPN6rclcpp4NodeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt8functionIFvRKSt10shared_ptrIKN11sensor_msgs3msg6Image_ISaIvEEEEEESA_17rmw_qos_profile_t
[ERROR] [component_container-3]: process has died [pid 4674, exit code 127, cmd '/opt/ros/foxy/lib/rclcpp_components/component_container --ros-args -r __node:=container -r __ns:=/'].
[ERROR] [component_container-4]: process has died [pid 4676, exit code 127, cmd '/opt/ros/foxy/lib/rclcpp_components/component_container --ros-args -r __node:=container2 -r __ns:=/'].
[rviz2-5] [INFO] [1650351343.643232265] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-5] [INFO] [1650351343.643346811] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-5] [INFO] [1650351343.687398783] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-5] [INFO] [1650351343.799307499] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-5] Parsing robot urdf xml string.
[stereo_inertial_node-1] terminate called after throwing an instance of 'std::runtime_error'
[stereo_inertial_node-1]   what():  There is no Camera data available corresponding to the the requested cameraId
[stereo_inertial_node-1] Stack trace (most recent call last):
[stereo_inertial_node-1] #11   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
[stereo_inertial_node-1] #10   Object "/home/igcs/ros2_depthai_ws/install/depthai_examples/lib/depthai_examples/stereo_inertial_node", at 0x55c47bfe13bd, in 
[stereo_inertial_node-1] #9    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f157e8370b2, in __libc_start_main
[stereo_inertial_node-1] #8    Object "/home/igcs/ros2_depthai_ws/install/depthai_examples/lib/depthai_examples/stereo_inertial_node", at 0x55c47bfe42ff, in 
[stereo_inertial_node-1] #7    Object "/home/igcs/ros2_depthai_ws/install/depthai_bridge/lib/libdepthai_bridge.so", at 0x7f1580816d46, in dai::ros::ImageConverter::calibrationToCameraInfo(dai::CalibrationHandler, dai::CameraBoardSocket, int, int, dai::Point2f, dai::Point2f)
[stereo_inertial_node-1] #6    Object "/home/igcs/depthai-core/build/install/lib/libdepthai-core.so", at 0x7f157f9f61bf, in dai::CalibrationHandler::getDefaultIntrinsics(dai::CameraBoardSocket)
[stereo_inertial_node-1] #5    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f157eaca6a8, in __cxa_throw
[stereo_inertial_node-1] #4    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f157eaca3f6, in std::terminate()
[stereo_inertial_node-1] #3    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f157eaca38b, in 
[stereo_inertial_node-1] #2    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f157eabe910, in 
[stereo_inertial_node-1] #1    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f157e835858, in abort
[stereo_inertial_node-1] #0    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f157e85603b, in gsignal
[stereo_inertial_node-1] Aborted (Signal sent by tkill() 4670 1000)
[ERROR] [stereo_inertial_node-1]: process has died [pid 4670, exit code -6, cmd '/home/igcs/ros2_depthai_ws/install/depthai_examples/lib/depthai_examples/stereo_inertial_node --ros-args --params-file /tmp/launch_params_krenjejt --params-file /tmp/launch_params_xwi6s05e --params-file /tmp/launch_params_ra1y9ab8 --params-file /tmp/launch_params_f_aq2ob6 --params-file /tmp/launch_params_hv9k2ese --params-file /tmp/launch_params_nx6t9jjr --params-file /tmp/launch_params_pzt5_ild --params-file /tmp/launch_params_4hqec7ds --params-file /tmp/launch_params_uyydqrfn --params-file /tmp/launch_params_zsy3z0pk --params-file /tmp/launch_params_8fjida68'].
[INFO] [rviz2-5]: process has finished cleanly [pid 4678]
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[robot_state_publisher-2] [INFO] [1650351357.779730886] [rclcpp]: signal_handler(signal_value=2)
[INFO] [robot_state_publisher-2]: process has finished cleanly [pid 4672]
[WARNING] [launch_ros.actions.load_composable_nodes]: Abandoning wait for the '/container/_container/load_node' service response, due to shutdown.
[WARNING] [launch_ros.actions.load_composable_nodes]: Abandoning wait for the '/container2/_container/load_node' service response, due to shutdown.
igcs@igcs:~$ 
`

If I run rgb_stereo
`[INFO] [launch]: All log files can be found below /home/igcs/.ros/log/2022-04-19-07-57-36-386586-igcs-4860
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rgb_stereo_node-1]: process started with pid [4863]
[INFO] [robot_state_publisher-2]: process started with pid [4865]
[robot_state_publisher-2] Parsing robot urdf xml string.
[robot_state_publisher-2] Link oak-d_frame had 5 children
[robot_state_publisher-2] Link oak_imu_frame had 0 children
[robot_state_publisher-2] Link oak_left_camera_frame had 1 children
[robot_state_publisher-2] Link oak_left_camera_optical_frame had 0 children
[robot_state_publisher-2] Link oak_model_origin had 0 children
[robot_state_publisher-2] Link oak_rgb_camera_frame had 1 children
[robot_state_publisher-2] Link oak_rgb_camera_optical_frame had 0 children
[robot_state_publisher-2] Link oak_right_camera_frame had 1 children
[robot_state_publisher-2] Link oak_right_camera_optical_frame had 0 children
[robot_state_publisher-2] [INFO] [1650351456.584738672] [oak_state_publisher]: got segment oak-d-base-frame
[robot_state_publisher-2] [INFO] [1650351456.584799226] [oak_state_publisher]: got segment oak-d_frame
[robot_state_publisher-2] [INFO] [1650351456.584810750] [oak_state_publisher]: got segment oak_imu_frame
[robot_state_publisher-2] [INFO] [1650351456.584821157] [oak_state_publisher]: got segment oak_left_camera_frame
[robot_state_publisher-2] [INFO] [1650351456.584831633] [oak_state_publisher]: got segment oak_left_camera_optical_frame
[robot_state_publisher-2] [INFO] [1650351456.584841272] [oak_state_publisher]: got segment oak_model_origin
[robot_state_publisher-2] [INFO] [1650351456.584852097] [oak_state_publisher]: got segment oak_rgb_camera_frame
[robot_state_publisher-2] [INFO] [1650351456.584862155] [oak_state_publisher]: got segment oak_rgb_camera_optical_frame
[robot_state_publisher-2] [INFO] [1650351456.584872771] [oak_state_publisher]: got segment oak_right_camera_frame
[robot_state_publisher-2] [INFO] [1650351456.584883527] [oak_state_publisher]: got segment oak_right_camera_optical_frame
[rgb_stereo_node-1] [14442C1071EB3FD700] [111.866] [system] [error] Attempted to start Color camera - NOT detected!
[rgb_stereo_node-1] terminate called after throwing an instance of 'std::runtime_error'
[rgb_stereo_node-1]   what():  There is no Camera data available corresponding to the the requested cameraId
[rgb_stereo_node-1] Stack trace (most recent call last):
[rgb_stereo_node-1] #11   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
[rgb_stereo_node-1] #10   Object "/home/igcs/ros2_depthai_ws/install/depthai_examples/lib/depthai_examples/rgb_stereo_node", at 0x55eb06ae327d, in 
[rgb_stereo_node-1] #9    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7ff998e5c0b2, in __libc_start_main
[rgb_stereo_node-1] #8    Object "/home/igcs/ros2_depthai_ws/install/depthai_examples/lib/depthai_examples/rgb_stereo_node", at 0x55eb06ae58d7, in 
[rgb_stereo_node-1] #7    Object "/home/igcs/ros2_depthai_ws/install/depthai_bridge/lib/libdepthai_bridge.so", at 0x7ff99ae36d46, in dai::ros::ImageConverter::calibrationToCameraInfo(dai::CalibrationHandler, dai::CameraBoardSocket, int, int, dai::Point2f, dai::Point2f)
[rgb_stereo_node-1] #6    Object "/home/igcs/depthai-core/build/install/lib/libdepthai-core.so", at 0x7ff99a01b1bf, in dai::CalibrationHandler::getDefaultIntrinsics(dai::CameraBoardSocket)
[rgb_stereo_node-1] #5    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7ff9990ef6a8, in __cxa_throw
[rgb_stereo_node-1] #4    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7ff9990ef3f6, in std::terminate()
[rgb_stereo_node-1] #3    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7ff9990ef38b, in 
[rgb_stereo_node-1] #2    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7ff9990e3910, in 
[rgb_stereo_node-1] #1    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7ff998e5a858, in abort
[rgb_stereo_node-1] #0    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7ff998e7b03b, in gsignal
[rgb_stereo_node-1] Aborted (Signal sent by tkill() 4863 1000)
[ERROR] [rgb_stereo_node-1]: process has died [pid 4863, exit code -6, cmd '/home/igcs/ros2_depthai_ws/install/depthai_examples/lib/depthai_examples/rgb_stereo_node --ros-args --params-file /tmp/launch_params_rpe6y3k5 --params-file /tmp/launch_params_hld3jbzb --params-file /tmp/launch_params_ho_y_4jl --params-file /tmp/launch_params_bfzxex29 --params-file /tmp/launch_params_u3u972s6 --params-file /tmp/launch_params_toggfmy5 --params-file /tmp/launch_params_0r2lcpix --params-file /tmp/launch_params_pr7fi6ux --params-file /tmp/launch_params_hpoj7hpp --params-file /tmp/launch_params_2u43061y --params-file /tmp/launch_params_hxxjdosq --params-file /tmp/launch_params__sbswrzs'].
`

**Comment by FPSychotic** [comment]
If I run yolo4 whatever, different error

` ros2 launch depthai_examples yolov4_publisher.launch.py
[INFO] [launch]: All log files can be found below /home/igcs/.ros/log/2022-04-19-08-02-29-666155-igcs-5021
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:226> exception=TypeError("Allowed value types are bytes, bool, int, float, str, Sequence[bool], Sequence[int], Sequence[float], Sequence[str]. Got <class 'NoneType'>.If the parameter is meant to be a string, try wrapping it in launch_ros.parameter_descriptions.ParameterValue(value, value_type=str)")>
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  [Previous line repeated 1 more time]
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/node.py", line 444, in execute
    self._perform_substitutions(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/node.py", line 399, in _perform_substitutions
    evaluated_parameters = evaluate_parameters(context, self.__parameters)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/utilities/evaluate_parameters.py", line 160, in evaluate_parameters
    output_params.append(evaluate_parameter_dict(context, param))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/utilities/evaluate_parameters.py", line 95, in evaluate_parameter_dict
    raise TypeError(
TypeError: Allowed value types are bytes, bool, int, float, str, Sequence[bool], Sequence[int], Sequence[float], Sequence[str]. Got <class 'NoneType'>.If the parameter is meant to be a string, try wrapping it in launch_ros.parameter_descriptions.ParameterValue(value, value_type=str)
`

It was  a clean installation.

**Comment by saching13** [comment]
> [stereo_inertial_node-1] what(): There is no Camera data available corresponding to the the requested cameraId

Your camera is not calibrated. I checked with Nejc. 
he said he didn't calibrate any Dev versions. 

Sorry for any miscommunications that might have happened on Discord

**Comment by FPSychotic** [comment]
> > [stereo_inertial_node-1] what(): There is no Camera data available corresponding to the the requested cameraId
> 
> Your camera is not calibrated. I checked with Nejc. he said he didn't calibrate any Dev versions.
> 
> Sorry for any miscommunications that might have happened on Discord

I understood by this message it would be calibrated.
I will post the issues from now here, as it looks that in Discord there is issues. I will try recover the time, but I was waiting 3 weeks something be integrated in ROS.

"You will get a board with OV9782 WFOV color camera and OV9282 WFOV mono cameras already installed on the board. So the cameras work out of box already. But active illumination is not supported yet, as they share an I2C bus with the cameras'.

In Discord we checked with a python script and worked, Alex I think was, said if it ls not calibrated, wont work, and worked, so we assumed it was calibrated.


By the way, ask please support the illuminator, it is what make them PRO XD.

And just confirm, what branch should I use to calibrate? Do you have any picture I can put in a 42" tv  to calibrate, is the only thing I have.

I hate calibrate I have not proper stuff

**Comment by saching13** [comment]
> In Discord we checked with a python script and worked, Alex I think was, said if it ls not calibrated, wont work, and worked, so we assumed it was calibrated.

When he says it won't work. it means you won't get valid depth. In ros we need to publish the Camera Info so Calibration is needed here.  Sorry for the miscommunication. 

> By the way, ask please support the illuminator, it is what make them PRO XD.

Will add this to the Stereo inertial node today. 

> And just confirm, what branch should I use to calibrate? Do you have any picture I can put in a 42" tv to calibrate, is the only thing I have.

you can use main if this is not a custom version of OAK-D Pro W. 
Does it has 2 OV9282 and 1 OV9782 ?

**Comment by FPSychotic** [comment]
Yes , it is a standard Pro W, probably as the project use 3D lidar and make interference I will add two color stereo modules and the IR in the center. But not now, maybe I add notch filter or buy filtered IR sendor.But would be nice have support to different sensor combinations in ROS, anyways I guess the one that have like rpi modules I guess need that too

**Comment by saching13** [comment]
if it's a standard one you should be able to calibrate on main branch of `depthai` repo

**Comment by FPSychotic** [comment]
> if it's a standard one you should be able to calibrate on main branch of `depthai` repo

Sorry , only for calibration, or I just can install main with the pro W
Untill now I need Warp branch

**Comment by FPSychotic** [comment]
Untill now I need Warp branch

**Comment by saching13** [comment]
that you did on C++ right. Not for python. If for python also it should be fine I think but better to follow the steps in the link below


[https://docs.luxonis.com/en/latest/pages/calibration/](https://docs.luxonis.com/en/latest/pages/calibration/)

**Comment by FPSychotic** [comment]
> you did on C++ right. Not for python

That doesn't work.
I cannot use the camera in ROS because it is not calibrated.
I need calibrate it to have the rgb recognised
I need the rgb recognized to can calibrate.
The fov in the .json file doesn't match with adviced fov either.
So what I do next.

![20220427_134719](https://user-images.githubusercontent.com/36112212/165561533-8d3378e2-1ef7-4fd8-a331-0d01c8208fee.jpg)

**Comment by saching13** [comment]
replied on discord. 
need to use [this](this) branch for OAK-D-Pro-W

**Comment by FPSychotic** [comment]
So rgb exmples not working?

For what add something that leave a sensor off of game?

Could be that any panameter in my inertial stereo example is calling a RGB
function and because that stereo inertial crash?

If not, Im afraid that I received another camera without calibration
