### ISSUE TITLE
Specific for Robot and Host Desktop CPU configurations “no rviz” and “rviz only” launch packages

### ISSUE THREAD

**Issue by ARLunan** [luxonis/depthai-ros-examples#42]
Create ROS2 Packages, 1) with an image Topic Publish only - “stereo_inertial_launch.py -no rviz node launch file to run on a Robot CPU, to publish topics to be displayed by a 2) new Package comprising reduced code “rviz only” launch.py file installed on a separate Host Desktop CPU that manages and controls the Robot.

**Comment by ARLunan** [comment]
- [ ]

**Comment by danilo-pejovic** [comment]
Since monolithic node offers options to run all our nodes with/without rviz visualization I will close this issue as completed.
