### ISSUE TITLE
Specific ROS2 Foxy Robot CPU “no rviz” and Host Desktop “rviz”only” Packages 

### ISSUE THREAD

**Issue by ARLunan** [luxonis/depthai-ros-examples#43]
Create ROS2 Packages, 1) with an image Topic Publish only - “stereo_inertial_launch.py -no rviz node launch file to run on a Robot CPU, to publish topics to be displayed by a 2) new Package comprising reduced code “rviz only” launch.py file installed on a separate Host Desktop CPU that manages and controls the Robot.

**Comment by saching13** [comment]
Duplicate of #42
