### ISSUE TITLE
Feature request: Enable/disable camera through ROS2 service

### ISSUE THREAD

**Issue by roni-kreinin** [luxonis/depthai-ros-examples#59]
It would be useful to be able to enable/disable the camera streams at runtime or put the camera into a low power state when not in use, without actually killing the ROS2 node. This could be done with a [SetBool](http://docs.ros.org/en/api/std_srvs/html/srv/SetBool.html) service.

**Comment by danilo-pejovic** [comment]
Considering this issue is already moved to more suitable repository, I will close it.
