### ISSUE TITLE
Different fps for video and preview output

### ISSUE THREAD

**Issue by alexswerner** [luxonis/depthai-ros-examples#61]
Is it possible to modify the code such that the frame rates for video and preview output are different? I'm using the camera on a resource contraint platform and want to lower the computational burden. As an example I would like to have 30 fps for the preview output and 2 fps for the video output.

Alternatively, could there be a ROS service to capture still images at the full sensor resolution?

**Comment by danilo-pejovic** [comment]
We are cleaning up this repository as we intend to use it for some use cases of our ROS nodes - as this is already moved to depthai-ros I think it is safe to close this issue here.
