### ISSUE TITLE
fatal error. Please report to developers. Log: 'PlgSrcMipi' '981'

### ISSUE THREAD

**Issue by Neo-cyber-hubb** [luxonis/depthai-ros-examples#62]

**Comment by Neo-cyber-hubb** [comment]
Hello! My device is OAK-FFC-4P. I encountered this problem when I tried to publish images through rgb_publisher node.

**Comment by saching13** [comment]
Error from core. Moved to `depthai-ros`

**Comment by Neo-cyber-hubb** [comment]
Thanks!
